=begin
#KeyVaultClient

#The key vault client performs cryptographic key operations and vault operations against the Key Vault service.

OpenAPI spec version: 7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DeletedCertificatesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeletedCertificatesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DeletedCertificatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeletedCertificatesApi' do
    it 'should create an instance of DeletedCertificatesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DeletedCertificatesApi)
    end
  end

  # unit tests for get_deleted_certificate
  # Retrieves information about the specified deleted certificate.
  # The GetDeletedCertificate operation retrieves the deleted certificate information plus its attributes, such as retention interval, scheduled permanent deletion and the current deletion recovery level. This operation requires the certificates/get permission.
  # @param certificate_name The name of the certificate
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [DeletedCertificateBundle]
  describe 'get_deleted_certificate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_deleted_certificates
  # Lists the deleted certificates in the specified vault currently available for recovery.
  # The GetDeletedCertificates operation retrieves the certificates in the current vault which are in a deleted state and ready for recovery or purging. This operation includes deletion-specific information. This operation requires the certificates/get/list permission. This operation can only be enabled on soft-delete enabled vaults.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :maxresults Maximum number of results to return in a page. If not specified the service will return up to 25 results.
  # @option opts [BOOLEAN] :include_pending Specifies whether to include certificates which are not completely provisioned.
  # @return [DeletedCertificateListResult]
  describe 'get_deleted_certificates test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for purge_deleted_certificate
  # Permanently deletes the specified deleted certificate.
  # The PurgeDeletedCertificate operation performs an irreversible deletion of the specified certificate, without possibility for recovery. The operation is not available if the recovery level does not specify &#39;Purgeable&#39;. This operation requires the certificate/purge permission.
  # @param certificate_name The name of the certificate
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'purge_deleted_certificate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for recover_deleted_certificate
  # Recovers the deleted certificate back to its current version under /certificates.
  # The RecoverDeletedCertificate operation performs the reversal of the Delete operation. The operation is applicable in vaults enabled for soft-delete, and must be issued during the retention interval (available in the deleted certificate&#39;s attributes). This operation requires the certificates/recover permission.
  # @param certificate_name The name of the deleted certificate
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [CertificateBundle]
  describe 'recover_deleted_certificate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
