=begin
#KeyVaultClient

#The key vault client performs cryptographic key operations and vault operations against the Key Vault service.

OpenAPI spec version: 7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::KeysApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'KeysApi' do
  before do
    # run before each test
    @instance = SwaggerClient::KeysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeysApi' do
    it 'should create an instance of KeysApi' do
      expect(@instance).to be_instance_of(SwaggerClient::KeysApi)
    end
  end

  # unit tests for backup_key
  # Requests that a backup of the specified key be downloaded to the client.
  # The Key Backup operation exports a key from Azure Key Vault in a protected form. Note that this operation does NOT return key material in a form that can be used outside the Azure Key Vault system, the returned key material is either protected to a Azure Key Vault HSM or to Azure Key Vault itself. The intent of this operation is to allow a client to GENERATE a key in one Azure Key Vault instance, BACKUP the key, and then RESTORE it into another Azure Key Vault instance. The BACKUP operation may be used to export, in protected form, any key type from Azure Key Vault. Individual versions of a key cannot be backed up. BACKUP / RESTORE can be performed within geographical boundaries only; meaning that a BACKUP from one geographical area cannot be restored to another geographical area. For example, a backup from the US geographical area cannot be restored in an EU geographical area. This operation requires the key/backup permission.
  # @param key_name The name of the key.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [BackupKeyResult]
  describe 'backup_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_key
  # Creates a new key, stores it, then returns key parameters and attributes to the client.
  # The create key operation can be used to create any key type in Azure Key Vault. If the named key already exists, Azure Key Vault creates a new version of the key. It requires the keys/create permission.
  # @param key_name The name for the new key. The system will generate the version name for the new key.
  # @param parameters The parameters to create a key.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyBundle]
  describe 'create_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for decrypt
  # Decrypts a single block of encrypted data.
  # The DECRYPT operation decrypts a well-formed block of ciphertext using the target encryption key and specified algorithm. This operation is the reverse of the ENCRYPT operation; only a single block of data may be decrypted, the size of this block is dependent on the target key and the algorithm to be used. The DECRYPT operation applies to asymmetric and symmetric keys stored in Azure Key Vault since it uses the private portion of the key. This operation requires the keys/decrypt permission.
  # @param key_name The name of the key.
  # @param key_version The version of the key.
  # @param parameters The parameters for the decryption operation.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyOperationResult]
  describe 'decrypt test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_key
  # Deletes a key of any type from storage in Azure Key Vault.
  # The delete key operation cannot be used to remove individual versions of a key. This operation removes the cryptographic material associated with the key, which means the key is not usable for Sign/Verify, Wrap/Unwrap or Encrypt/Decrypt operations. This operation requires the keys/delete permission.
  # @param key_name The name of the key to delete.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [DeletedKeyBundle]
  describe 'delete_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for encrypt
  # Encrypts an arbitrary sequence of bytes using an encryption key that is stored in a key vault.
  # The ENCRYPT operation encrypts an arbitrary sequence of bytes using an encryption key that is stored in Azure Key Vault. Note that the ENCRYPT operation only supports a single block of data, the size of which is dependent on the target key and the encryption algorithm to be used. The ENCRYPT operation is only strictly necessary for symmetric keys stored in Azure Key Vault since protection with an asymmetric key can be performed using public portion of the key. This operation is supported for asymmetric keys as a convenience for callers that have a key-reference but do not have access to the public key material. This operation requires the keys/encrypt permission.
  # @param key_name The name of the key.
  # @param key_version The version of the key.
  # @param parameters The parameters for the encryption operation.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyOperationResult]
  describe 'encrypt test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_key
  # Gets the public part of a stored key.
  # The get key operation is applicable to all key types. If the requested key is symmetric, then no key material is released in the response. This operation requires the keys/get permission.
  # @param key_name The name of the key to get.
  # @param key_version Adding the version parameter retrieves a specific version of a key. This URI fragment is optional. If not specified, the latest version of the key is returned.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyBundle]
  describe 'get_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_key_versions
  # Retrieves a list of individual key versions with the same key name.
  # The full key identifier, attributes, and tags are provided in the response. This operation requires the keys/list permission.
  # @param key_name The name of the key.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :maxresults Maximum number of results to return in a page. If not specified the service will return up to 25 results.
  # @return [KeyListResult]
  describe 'get_key_versions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_keys
  # List keys in the specified vault.
  # Retrieves a list of the keys in the Key Vault as JSON Web Key structures that contain the public part of a stored key. The LIST operation is applicable to all key types, however only the base key identifier, attributes, and tags are provided in the response. Individual versions of a key are not listed in the response. This operation requires the keys/list permission.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :maxresults Maximum number of results to return in a page. If not specified the service will return up to 25 results.
  # @return [KeyListResult]
  describe 'get_keys test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for import_key
  # Imports an externally created key, stores it, and returns key parameters and attributes to the client.
  # The import key operation may be used to import any key type into an Azure Key Vault. If the named key already exists, Azure Key Vault creates a new version of the key. This operation requires the keys/import permission.
  # @param key_name Name for the imported key.
  # @param parameters The parameters to import a key.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyBundle]
  describe 'import_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for restore_key
  # Restores a backed up key to a vault.
  # Imports a previously backed up key into Azure Key Vault, restoring the key, its key identifier, attributes and access control policies. The RESTORE operation may be used to import a previously backed up key. Individual versions of a key cannot be restored. The key is restored in its entirety with the same key name as it had when it was backed up. If the key name is not available in the target Key Vault, the RESTORE operation will be rejected. While the key name is retained during restore, the final key identifier will change if the key is restored to a different vault. Restore will restore all versions and preserve version identifiers. The RESTORE operation is subject to security constraints: The target Key Vault must be owned by the same Microsoft Azure Subscription as the source Key Vault The user must have RESTORE permission in the target Key Vault. This operation requires the keys/restore permission.
  # @param parameters The parameters to restore the key.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyBundle]
  describe 'restore_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sign
  # Creates a signature from a digest using the specified key.
  # The SIGN operation is applicable to asymmetric and symmetric keys stored in Azure Key Vault since this operation uses the private portion of the key. This operation requires the keys/sign permission.
  # @param key_name The name of the key.
  # @param key_version The version of the key.
  # @param parameters The parameters for the signing operation.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyOperationResult]
  describe 'sign test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for unwrap_key
  # Unwraps a symmetric key using the specified key that was initially used for wrapping that key.
  # The UNWRAP operation supports decryption of a symmetric key using the target key encryption key. This operation is the reverse of the WRAP operation. The UNWRAP operation applies to asymmetric and symmetric keys stored in Azure Key Vault since it uses the private portion of the key. This operation requires the keys/unwrapKey permission.
  # @param key_name The name of the key.
  # @param key_version The version of the key.
  # @param parameters The parameters for the key operation.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyOperationResult]
  describe 'unwrap_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_key
  # The update key operation changes specified attributes of a stored key and can be applied to any key type and key version stored in Azure Key Vault.
  # In order to perform this operation, the key must already exist in the Key Vault. Note: The cryptographic material of a key itself cannot be changed. This operation requires the keys/update permission.
  # @param key_name The name of key to update.
  # @param key_version The version of the key to update.
  # @param parameters The parameters of the key to update.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyBundle]
  describe 'update_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for verify
  # Verifies a signature using a specified key.
  # The VERIFY operation is applicable to symmetric keys stored in Azure Key Vault. VERIFY is not strictly necessary for asymmetric keys stored in Azure Key Vault since signature verification can be performed using the public portion of the key but this operation is supported as a convenience for callers that only have a key-reference and not the public portion of the key. This operation requires the keys/verify permission.
  # @param key_name The name of the key.
  # @param key_version The version of the key.
  # @param parameters The parameters for verify operations.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyVerifyResult]
  describe 'verify test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for wrap_key
  # Wraps a symmetric key using a specified key.
  # The WRAP operation supports encryption of a symmetric key using a key encryption key that has previously been stored in an Azure Key Vault. The WRAP operation is only strictly necessary for symmetric keys stored in Azure Key Vault since protection with an asymmetric key can be performed using the public portion of the key. This operation is supported for asymmetric keys as a convenience for callers that have a key-reference but do not have access to the public key material. This operation requires the keys/wrapKey permission.
  # @param key_name The name of the key.
  # @param key_version The version of the key.
  # @param parameters The parameters for wrap operation.
  # @param api_version Client API version.
  # @param [Hash] opts the optional parameters
  # @return [KeyOperationResult]
  describe 'wrap_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
