=begin
#KeyVaultClient

#The key vault client performs cryptographic key operations and vault operations against the Key Vault service.

OpenAPI spec version: 7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::KeyUpdateParameters
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'KeyUpdateParameters' do
  before do
    # run before each test
    @instance = SwaggerClient::KeyUpdateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeyUpdateParameters' do
    it 'should create an instance of KeyUpdateParameters' do
      expect(@instance).to be_instance_of(SwaggerClient::KeyUpdateParameters)
    end
  end
  describe 'test attribute "key_ops"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["encrypt", "decrypt", "sign", "verify", "wrapKey", "unwrapKey"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.key_ops = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "attributes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tags"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
