=begin
#KeyVaultClient

#The key vault client performs cryptographic key operations and vault operations against the Key Vault service.

OpenAPI spec version: 7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::KeyVerifyParameters
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'KeyVerifyParameters' do
  before do
    # run before each test
    @instance = SwaggerClient::KeyVerifyParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeyVerifyParameters' do
    it 'should create an instance of KeyVerifyParameters' do
      expect(@instance).to be_instance_of(SwaggerClient::KeyVerifyParameters)
    end
  end
  describe 'test attribute "alg"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["PS256", "PS384", "PS512", "RS256", "RS384", "RS512", "RSNULL", "ES256", "ES384", "ES512", "ES256K"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.alg = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "digest"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
