=begin
#KeyVaultClient

#The key vault client performs cryptographic key operations and vault operations against the Key Vault service.

OpenAPI spec version: 7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/action'
require 'swagger_client/models/administrator_details'
require 'swagger_client/models/attributes'
require 'swagger_client/models/backup_certificate_result'
require 'swagger_client/models/backup_key_result'
require 'swagger_client/models/backup_secret_result'
require 'swagger_client/models/backup_storage_result'
require 'swagger_client/models/certificate_attributes'
require 'swagger_client/models/certificate_bundle'
require 'swagger_client/models/certificate_create_parameters'
require 'swagger_client/models/certificate_import_parameters'
require 'swagger_client/models/certificate_issuer_item'
require 'swagger_client/models/certificate_issuer_list_result'
require 'swagger_client/models/certificate_issuer_set_parameters'
require 'swagger_client/models/certificate_issuer_update_parameters'
require 'swagger_client/models/certificate_item'
require 'swagger_client/models/certificate_list_result'
require 'swagger_client/models/certificate_merge_parameters'
require 'swagger_client/models/certificate_operation'
require 'swagger_client/models/certificate_operation_update_parameter'
require 'swagger_client/models/certificate_policy'
require 'swagger_client/models/certificate_restore_parameters'
require 'swagger_client/models/certificate_update_parameters'
require 'swagger_client/models/contact'
require 'swagger_client/models/contacts'
require 'swagger_client/models/deleted_certificate_bundle'
require 'swagger_client/models/deleted_certificate_item'
require 'swagger_client/models/deleted_certificate_list_result'
require 'swagger_client/models/deleted_key_bundle'
require 'swagger_client/models/deleted_key_item'
require 'swagger_client/models/deleted_key_list_result'
require 'swagger_client/models/deleted_sas_definition_bundle'
require 'swagger_client/models/deleted_sas_definition_item'
require 'swagger_client/models/deleted_sas_definition_list_result'
require 'swagger_client/models/deleted_secret_bundle'
require 'swagger_client/models/deleted_secret_item'
require 'swagger_client/models/deleted_secret_list_result'
require 'swagger_client/models/deleted_storage_account_item'
require 'swagger_client/models/deleted_storage_bundle'
require 'swagger_client/models/deleted_storage_list_result'
require 'swagger_client/models/error'
require 'swagger_client/models/issuer_attributes'
require 'swagger_client/models/issuer_bundle'
require 'swagger_client/models/issuer_credentials'
require 'swagger_client/models/issuer_parameters'
require 'swagger_client/models/json_web_key'
require 'swagger_client/models/key_attributes'
require 'swagger_client/models/key_bundle'
require 'swagger_client/models/key_create_parameters'
require 'swagger_client/models/key_import_parameters'
require 'swagger_client/models/key_item'
require 'swagger_client/models/key_list_result'
require 'swagger_client/models/key_operation_result'
require 'swagger_client/models/key_operations_parameters'
require 'swagger_client/models/key_properties'
require 'swagger_client/models/key_restore_parameters'
require 'swagger_client/models/key_sign_parameters'
require 'swagger_client/models/key_update_parameters'
require 'swagger_client/models/key_vault_error'
require 'swagger_client/models/key_verify_parameters'
require 'swagger_client/models/key_verify_result'
require 'swagger_client/models/lifetime_action'
require 'swagger_client/models/organization_details'
require 'swagger_client/models/pending_certificate_signing_request_result'
require 'swagger_client/models/sas_definition_attributes'
require 'swagger_client/models/sas_definition_bundle'
require 'swagger_client/models/sas_definition_create_parameters'
require 'swagger_client/models/sas_definition_item'
require 'swagger_client/models/sas_definition_list_result'
require 'swagger_client/models/sas_definition_update_parameters'
require 'swagger_client/models/secret_attributes'
require 'swagger_client/models/secret_bundle'
require 'swagger_client/models/secret_item'
require 'swagger_client/models/secret_list_result'
require 'swagger_client/models/secret_properties'
require 'swagger_client/models/secret_restore_parameters'
require 'swagger_client/models/secret_set_parameters'
require 'swagger_client/models/secret_update_parameters'
require 'swagger_client/models/storage_account_attributes'
require 'swagger_client/models/storage_account_create_parameters'
require 'swagger_client/models/storage_account_item'
require 'swagger_client/models/storage_account_regenerte_key_parameters'
require 'swagger_client/models/storage_account_update_parameters'
require 'swagger_client/models/storage_bundle'
require 'swagger_client/models/storage_list_result'
require 'swagger_client/models/storage_restore_parameters'
require 'swagger_client/models/subject_alternative_names'
require 'swagger_client/models/trigger'
require 'swagger_client/models/x509_certificate_properties'

# APIs
require 'swagger_client/api/certificates_api'
require 'swagger_client/api/deleted_certificates_api'
require 'swagger_client/api/deleted_keys_api'
require 'swagger_client/api/deleted_secrets_api'
require 'swagger_client/api/deleted_storage_api'
require 'swagger_client/api/keys_api'
require 'swagger_client/api/secrets_api'
require 'swagger_client/api/storage_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
